#!/bin/csh
#
echo  compute charges for an anion and optimize with BOSS
#     starting from a z-matrix ionname -
#     this is used to refine an initial structure
#     of a monocation. CM1A charges are unscaled.
#
# usage - xZCM1A- ionname
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp $argv[1].z optzmat
csh $BOSSdir/scripts/AM1SP-cmd >& log
rm optzmat
#cp sum optzmat
#csh $BOSSdir/scripts/OPTcmd >& log 
#rm optzmat
#cp sum optzmat
#csh $BOSSdir/scripts/AM1SP-cmd >& log
#rm optzmat
#cp sum optzmat
#csh $BOSSdir/scripts/OPTcmd >& log 
#rm optzmat
#cp sum optzmat
#csh $BOSSdir/scripts/AM1SP-cmd >& log
#echo  output is in out, sum and plt.pdb
#rm optzmat
#cp sum optzmat
#csh $BOSSdir/scripts/OPTcmd >& log 
#rm optzmat
#
exit
